### ISSUE TITLE
Runtime-avhengighet i Java 17

### ISSUE THREAD

**Issue by kons-jaf** [felleslosninger/eid-statistikk-inndata-api#28]
Ved kjøring av **inndata-api** med Java 17 kreves en oppdatering av JAXB-avhengighetene.
Godt forklart her: https://mkyong.com/java/java-lang-classnotfoundexception-com-sun-xml-bind-v2-contextfactory/

**Comment by kometen** [comment]
Da skal det være korrigeret.
